from cgi import print_arguments
import time
import random
print('Hey there! You found this file, so you get a reward.')
time.sleep(1.5)
print('Its time to play...')
time.sleep(1.5)
print('BUST')
time.sleep(.5)
print('A')
time.sleep(.5)
print('MOVE!')
time.sleep(1.5)
print('Here are the rules:')
time.sleep(1.5)
print('When the computer says bust a move, you BUST A MOVE!')
time.sleep(2)
print('Ready?')
time.sleep(1.5)
print('BUST A MOVE!')
time.sleep(13.7)
print('STOP')
time.sleep(4.7)
print('BUST A MOVE!')
time.sleep(8.1)
print('STOP')
time.sleep(10)
print("BUST A MOVE!")
time.sleep(7)
print('Good job busting a move! See you next time!')
exit
